### ISSUE TITLE
Bots are flagging "bad packets" upon join with Vulcan anti-cheat

### ISSUE THREAD

**Issue by Cubxity** [PrismarineJS/mineflayer#2513]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: `4.0.0`
 - server: `git-Pufferfish-20 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b9556fd on HEAD)`
 - node: `16`

## Detailed description of a problem

Mineflayer bots flag Vulcan anti-cheat upon joining, due to the bots sending item held slot packet regardless of what the current held slot is.

![image](https://user-images.githubusercontent.com/27609129/156936220-e2be649b-6966-4aef-94dd-839fff2243ba.png)

## Expected behavior

It is expected that the bots don't send held item packet unless the held item slot changes.

## Additional context

Running Vulcan v2.6.2

**Comment by u9g** [comment]
this packet is sent in two places: https://github.com/PrismarineJS/mineflayer/blob/694bee68e90b890b6ac58e920122bf2472b3ebd5/lib/plugins/game.js#L70 and https://github.com/PrismarineJS/mineflayer/blob/4fe54ad05a8c68892534f8f7c78e77cbff8a67b5/lib/plugins/simple_inventory.js#L56

Is the bot flagging after a little bit or right after join?

**Comment by amoraschi** [comment]
I don't think bots are made to bypass anticheats, you can always fork the package and modify it

**Comment by Cubxity** [comment]
> this packet is sent in two places:
> 
> https://github.com/PrismarineJS/mineflayer/blob/694bee68e90b890b6ac58e920122bf2472b3ebd5/lib/plugins/game.js#L70
> and
> 
> https://github.com/PrismarineJS/mineflayer/blob/4fe54ad05a8c68892534f8f7c78e77cbff8a67b5/lib/plugins/simple_inventory.js#L56
> 
> Is the bot flagging after a little bit or right after join?

It is flagged right after joining.

**Comment by u9g** [comment]
> > this packet is sent in two places:
> > https://github.com/PrismarineJS/mineflayer/blob/694bee68e90b890b6ac58e920122bf2472b3ebd5/lib/plugins/game.js#L70
> > 
> > and
> > https://github.com/PrismarineJS/mineflayer/blob/4fe54ad05a8c68892534f8f7c78e77cbff8a67b5/lib/plugins/simple_inventory.js#L56
> > 
> > Is the bot flagging after a little bit or right after join?
> 
> It is flagged right after joining.

if you comment out the first thing line I quoted, does it still flag?

**Comment by Cubxity** [comment]
> > > this packet is sent in two places:
> > > https://github.com/PrismarineJS/mineflayer/blob/694bee68e90b890b6ac58e920122bf2472b3ebd5/lib/plugins/game.js#L70
> > > 
> > > and
> > > https://github.com/PrismarineJS/mineflayer/blob/4fe54ad05a8c68892534f8f7c78e77cbff8a67b5/lib/plugins/simple_inventory.js#L56
> > > 
> > > Is the bot flagging after a little bit or right after join?
> > 
> > 
> > It is flagged right after joining.
> 
> if you comment out the first thing line I quoted, does it still flag?

Commenting out the packet in game.js stops the AC from flagging, yes.

**Comment by u9g** [comment]
> > > > this packet is sent in two places:
> > > > https://github.com/PrismarineJS/mineflayer/blob/694bee68e90b890b6ac58e920122bf2472b3ebd5/lib/plugins/game.js#L70
> > > > 
> > > > and
> > > > https://github.com/PrismarineJS/mineflayer/blob/4fe54ad05a8c68892534f8f7c78e77cbff8a67b5/lib/plugins/simple_inventory.js#L56
> > > > 
> > > > Is the bot flagging after a little bit or right after join?
> > > 
> > > 
> > > It is flagged right after joining.
> > 
> > 
> > if you comment out the first thing line I quoted, does it still flag?
> 
> Commenting out the packet in game.js stops the AC from flagging, yes. It seems like `setQuickBarSlot(0)` is also called upon join, so I believe the one in `game.js` is redundant.

Hm, you can just make a variable then for the lastSentQuickbarSlot which starts at null, then check in the setQuickBarSlot to ensure we aren't sending the same quickbar slot twice in a row. (then pr that :P)

**Comment by U5B** [comment]
Fixed in my PR

**Comment by u9g** [comment]
> Fixed in my PR #2492
> 
> It removes the one in game.js because that one is unnecessary

can you put this in a seperate pr?

**Comment by U5B** [comment]
> 
> can you put this in a seperate pr?
 
I guess I could. That PR is supposed to fix most of the issues I had with anticheats which is why I included it in that PR. Once I get home, I'll make the PR.

**Comment by U5B** [comment]
@u9g PR created.

**Comment by FreshImmuc** [comment]
So, this issue is a bit old and i see the PR was already merged BUT i still get this same issue. I just got this anticheat message from a bot:

![Image](https://github.com/user-attachments/assets/4189288a-365c-4472-8054-a763f8998884)

The message comes right after join, just like the original issue.
